# Generated by Django 3.2.16 on 2022-12-24 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='curs_author', to='api.users', to_field='login', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='curs',
            name='members',
            field=models.ManyToManyField(related_name='curs_members', to='api.Users', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='lections',
            name='curs',
            field=models.ForeignKey(default='AAAAAAAA', on_delete=django.db.models.deletion.CASCADE, to='api.curs', to_field='code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
