# Generated by Django 3.2.16 on 2022-12-25 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221225_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curs',
            name='main_img',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/programaci%C3%B3n-codificaci%C3%B3n-de-concepto-plano-54998068.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='curs',
            name='preview_img',
            field=models.URLField(default='https://img.lovepik.com/original_origin_pic/19/01/08/5016ef557fa043da01371d7a86300fa3.png_wh860.png', max_length=500),
        ),
    ]
