# Generated by Django 3.2.16 on 2022-12-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221225_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='curs_author', to='api.users', to_field='login'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='members',
            field=models.ManyToManyField(related_name='curs_members', to='api.Users'),
        ),
    ]
