# Generated by Django 4.1.4 on 2022-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(max_length=500)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('release_format', models.CharField(max_length=255)),
                ('release_year', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('publishing', models.CharField(max_length=255)),
            ],
        ),
    ]
