# Generated by Django 4.1.4 on 2022-12-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MangaLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMangas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MangaLib.manga')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
