# Generated by Django 4.1.4 on 2022-12-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0002_usermangas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermangas',
            name='manga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MangaLib.manga'),
        ),
    ]
