# Generated by Django 4.1.1 on 2022-10-31 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.URLField(max_length=500)),
                ('publisher', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('rule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('preview', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('video', models.URLField(max_length=500)),
                ('userName', models.CharField(max_length=100)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
    ]
