# Generated by Django 4.1.1 on 2022-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='time',
        ),
        migrations.AddField(
            model_name='run',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
