# Generated by Django 4.1.1 on 2022-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_run_time_run_hours_run_minutes_run_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
