# Generated by Django 4.1.1 on 2022-11-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_run_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
